### ISSUE TITLE
ISO location and permissions  

### ISSUE THREAD

**Issue by array-in-a-matrix** [ArseLinuxOS-Development/ArseLinuxOS-ISO#3]
After building the ISO it is located in the parent of the project directory which may lead to confusion.
ISO should be within the project's repo.
Permissions of the ISO is owned root which should be changed to the user.

**Comment by LiamAEdwards** [comment]
While I agree it should end up in the projects repo, I wouldn't want it to be automatically built into the repo since if the build has issues it shouldn't be available. 

I do agree with the permissions though, but I think since the docker container needs to run with `--privileged=true`  it might prevent that from happening. 

Feel free to experiment.

**Comment by LiamAEdwards** [comment]
Cool, I'll take a look at adding that feature when I get some spare time.

**Comment by LiamAEdwards** [comment]
So looking at the permissions issue, it seems that doing this adds a lot of overhead. 

- You can't CHOWN in a Dockerfile since it doesn't actually change anything (Due to how docker images are layered)
- Adding the chown to the `build.sh` just means that someone will have to add that when they could just CHOWN themselves.
- If you create a user via Dockerfile with a homedir and get them to run `mkarchiso` it will error out since it required root.

At this point I don't think adding this feature is worth the effort.

**Comment by animeshn99** [comment]
Hi @LiamAEdwards
As we are mounting our host volume, i  think we can do this with docker run command using -u 

And one suggestion, instead of hardcoding user volume path we can make it dynamic by pointing to the current folder through ${PWD} or ./
```

version: '3'
services:
  arselinux-build:
    user: "${UID}" 
    container_name: arselinux-build
    image: 'arselinux:latest'
    restart: unless-stopped
    privileged: true
    volumes:
      - ./:/root/ArseLinuxOS-ISO
```
